#!/bin/bash

function _quick_memo() {
    if ! type gsed > /dev/null 2>&1; then
        echo "error: you need to install gsed (gnu-sed)"
        echo "install: brew install gnu-sed"
        return
    fi

    SELF=$(cd $(dirname $0); pwd)
    local quick_memo_dir="${SELF}/.data"
    mkdir -p ${quick_memo_dir}

    #header="## =====> $(date '+%Y%m%d %H:%M:%S') <=====\n\n"
    header="## =====> $(date) <=====\n\n"
    gsed -i -e "1s/^/${header}/" ${quick_memo_dir}/quick_memo.md
    vim ${quick_memo_dir}/quick_memo.md
}

_quick_memo $@
exit 0
